name: Update README.md

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "Asia/Shanghai"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Push Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Generate README.md
        run: npm run build --if-present
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PUSHTOKEN }}
          BRANCH_NAME: 'main'
